version: "3.9"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"

  otel-collector:
    image: otel/opentelemetry-collector:0.101.0
    command: ["--config", "/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml:ro
    ports:
      - "4317:4317"

  kafka:
    image: bitnami/kafka:3.7
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
    ports:
      - "9092:9092"

  api:
    build: .
    environment:
      - ES_ENABLED=true
      - ES_URL=http://elasticsearch:9200
      - OTEL_ENABLED=true
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
      - KAFKA_ENABLED=true
      - KAFKA_BOOTSTRAP=kafka:9092
      - LOG_LEVEL=INFO
      - API_KEY=devkey
    depends_on:
      - elasticsearch
      - otel-collector
      - kafka
    ports:
      - "8080:8080"

  worker:
    build: .
    command: ["python", "-m", "app.worker.es_consumer"]
    environment:
      - ES_ENABLED=true
      - ES_URL=http://elasticsearch:9200
      - OTEL_ENABLED=true
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
      - KAFKA_ENABLED=true
      - KAFKA_BOOTSTRAP=kafka:9092
      - LOG_LEVEL=INFO
    depends_on:
      - elasticsearch
      - otel-collector
      - kafka

  scheduler:
    build: .
    command: ["python", "-m", "app.worker.scheduler", "--config", "/config/schedules.yaml"]
    environment:
      - LOG_LEVEL=INFO
      - API_KEY=devkey
      - API_URL=http://api:8080
    volumes:
      - ./schedules.example.yaml:/config/schedules.yaml:ro
    depends_on:
      - api
      - elasticsearch
